Add types file to exports
Fixes `error TS7016: Could not find a declaration file for module
'vuemoji-picker'. '<path>/vuemoji-picker/dist/index.mjs' implicitly has
an 'any' type.
  There are types at '<PATH>/vuemoji-picker/dist/index.d.ts', but this
result could not be resolved when respecting package.json "exports".
The 'vuemoji-picker' library may need to update its package.json or
typings.`